### ISSUE TITLE
Unrecognized function at Line 223

### ISSUE THREAD

**Issue by SpencerLab-BIO** [juwellwwu/NCFLOWSPEED#1]
Hello, This is Christian Burns, the grad student collaborator from the Spencer lab who worked on the Negative Contrast Paper.
I was trying to run your program on some of our datasets, but I am getting the following error:
Unrecognized function or variable 'skeleton'.

Error in NCFLOWSPEED (line 223)
Img_Skeleton=logical(bwmorph(skeleton(Img_Input)>Skeleton_Length,'skel',Inf));

Do I need to download an additional skeleton plugin for matlab?
 
Also, I am running Matlab 2020a

**Comment by juwellwwu** [comment]
Hello Christian,
Thank you for letting me know about the issue! Yes, the following package from MATLAB File Exchange should be installed first:
https://www.mathworks.com/matlabcentral/fileexchange/11123-better-skeletonization

**Comment by SpencerLab-BIO** [comment]
Thanks, that solved the issue.
I will mention that I tried to have the program analyze a 500mb file(1024 x 512 pixels x 1030 frames) and matlab ended up using around 70gb of RAM. So I would recommend either mentioning a max file size or seeing if their are some ways to optimize the ram usage.
